/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4dca27e6-dac7-4271-92af-c508f0c2588e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xziIkUtFT",
    "aws_user_pools_web_client_id": "6e8ockjt9b84omo0h558eamnri",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://kh25ojpakncehkhmxhxezdh6mu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-z7q77w5eknai3lue35u3hzhjpm",
    "aws_user_files_s3_bucket": "myfirstawsapp61070413ef3f4cceb4a3eddf91016c4444418-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
